# Generated by Django 4.2.6 on 2023-12-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0002_alter_remind_repeat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='repeat_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
