# Generated by Django 4.2.6 on 2023-12-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_alter_email_email_alter_phone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.BigIntegerField(blank=True, verbose_name='Номер телефона'),
        ),
    ]
