# Generated by Django 4.2.6 on 2023-12-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0003_alter_militaryticket_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='number',
            field=models.BigIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='foreignpassport',
            name='number',
            field=models.BigIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='inn',
            name='inn',
            field=models.BigIntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='inn',
            name='number',
            field=models.BigIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='militaryticket',
            name='number',
            field=models.BigIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.BigIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='snils',
            name='number',
            field=models.BigIntegerField(verbose_name='Номер'),
        ),
    ]
