# Generated by Django 4.2.6 on 2023-12-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0003_alter_diploma_year_of_finish_edu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='number',
            field=models.BigIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='registration_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Регистрационный номер'),
        ),
    ]
